version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - ls -alt
artifacts:
  files:
    - application
    - .ebextensions/**/*
  #base-directory: 'target/my-web-app'
  
